safe:        true
auto:        true
server:      false
server_port: 4000
baseurl:    /
url: //chaseph.github.io

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date
paginate: 	 10